import { useMemo, useState, type ElementType } from 'react'
import {
  ArrowRight, BadgeCheck, CalendarDays, Check, ChevronRight, Clock3, Filter,
  Heart, MapPin, MessageCircle, PackageCheck, Search, ShieldCheck, SlidersHorizontal,
  Sparkles, Star, Tag, Users, Wallet,
} from 'lucide-react'
import { PROVIDERS, type ProviderConfig } from '../pages/ServiceDetailPage'
import { type BookedService, type Screen, useNav } from '../context/NavContext'

type Navigate = (screen: Screen, params?: any) => void
type CatalogItem = {
  id: string; provider: string; name: string; category: string; price: number; rating: string;
  reviews: string; image: string; heroImg?: string; providerImage?: string; description: string;
  distance: string; providerBg: string; providerEmoji: string
}

const providerColours = ['bg-blue-500', 'bg-rose-500', 'bg-cyan-500', 'bg-emerald-500', 'bg-violet-500', 'bg-amber-500']
const providerInitials = (name: string) => name.split(/\s+/).map(word => word[0]).join('').slice(0, 2).toUpperCase()
const normalizeCategory = (category: string) => category === 'Home Services' ? 'Home services' : category === 'Car Services' ? 'Car services' : category === 'Salon & Spa' ? 'Salon & spa' : category

const PWA_CATEGORIES = [
  ['cleaning', 'Cleaning', '/assets/cat-uniform-cleaning.png'], ['maintenance', 'Maintenance', '/assets/cat-uniform-handyman.png'],
  ['design', 'Design & branding', '/assets/cat-uniform-design.png'], ['gift', 'Gifts', '/assets/cat-uniform-gifts.png'],
  ['events', 'Events', '/assets/cat-uniform-events.png'], ['gov', 'Government', '/assets/cat-uniform-government.png'],
  ['hardware', 'Tech support', '/assets/cat-tech-support-clean-cutout.png'], ['language', 'Language', '/assets/cat-uniform-language.png'],
  ['health', 'Health & wellness', '/assets/cat-uniform-health-wellness.png'], ['education', 'Tutoring & training', '/assets/cat-tutoring-clean-cutout.png'],
  ['visuals', 'Media', '/assets/cat-uniform-media.png'], ['digital', 'Digital', '/assets/cat-uniform-digital.png'],
  ['car', 'Car services', '/assets/cat-car-services-user-exact.png'], ['home', 'Home services', '/assets/cat-uniform-home-services.png'],
  ['laundry', 'Laundry', '/assets/cat-uniform-laundry.png'], ['pets', 'Pets', '/assets/cat-pets-dog-cat-food.png'],
  ['delivery', 'Deliveries', '/assets/cat-uniform-delivery.png'], ['salon', 'Salon & spa', '/assets/cat-uniform-salon.png'],
  ['marketplace', 'Marketplace', '/assets/cat-uniform-marketplace.png'],
] as const

const CATEGORY_MAP: Record<string, string[]> = {
  cleaning: ['Home services'], home: ['Home services', 'Maintenance'], maintenance: ['Maintenance'], car: ['Car services'],
  salon: ['Salon & spa'], laundry: ['Laundry'], digital: ['Digital', 'Support'], hardware: ['Digital', 'Support'],
  design: ['Digital'], visuals: ['Digital'], education: ['Education'], language: ['Education'], health: ['Salon & spa'],
  delivery: ['Deliveries'], marketplace: ['Travel', 'Deliveries'], gift: ['Travel'], gov: ['Support'],
}

const supplemental: CatalogItem[] = [
  { id: 'pawcare-grooming', provider: 'PawCare Doha', name: 'Pet grooming', category: 'Pets', price: 85, rating: '4.8', reviews: '142', distance: '3.1 KM', image: '/assets/cat-pets-dog-cat-food.png', description: 'Gentle at-home grooming for cats and dogs.', providerBg: 'bg-blue-500', providerEmoji: 'PC' },
  { id: 'happy-tails-walk', provider: 'Happy Tails', name: 'Dog walking', category: 'Pets', price: 45, rating: '4.7', reviews: '96', distance: '2.4 KM', image: '/assets/cat-pets-dog-cat-food.png', description: 'A safe, reliable neighbourhood walk for your dog.', providerBg: 'bg-sky-500', providerEmoji: 'HT' },
  { id: 'vetvisit-checkup', provider: 'VetVisit Home', name: 'Home vet checkup', category: 'Pets', price: 150, rating: '4.9', reviews: '74', distance: '5.0 KM', image: '/assets/cat-pets-dog-cat-food.png', description: 'A professional veterinary checkup at home.', providerBg: 'bg-indigo-500', providerEmoji: 'VV' },
  { id: 'pearl-events-wedding', provider: 'Pearl Events Qatar', name: 'Wedding planning consultation', category: 'Events', price: 850, rating: '4.9', reviews: '128', distance: '3.4 KM', image: '/assets/cat-uniform-events.png', description: 'Thoughtful planning for a beautifully coordinated celebration.', providerBg: 'bg-blue-600', providerEmoji: 'PE' },
  { id: 'doha-moments-event', provider: 'Doha Moments', name: 'Event planning package', category: 'Events', price: 500, rating: '4.8', reviews: '94', distance: '4.1 KM', image: '/assets/cat-uniform-events.png', description: 'A complete event plan shaped around your guests and occasion.', providerBg: 'bg-indigo-500', providerEmoji: 'DM' },
  { id: 'stagecraft-corporate', provider: 'StageCraft Events', name: 'Corporate event setup', category: 'Events', price: 1200, rating: '4.7', reviews: '76', distance: '5.6 KM', image: '/assets/cat-uniform-events.png', description: 'Professional setup and coordination for corporate events.', providerBg: 'bg-amber-500', providerEmoji: 'SE' },
]

export const FULL_CATALOG: CatalogItem[] = [
  ...Object.values(PROVIDERS).flatMap((provider, providerIndex) => provider.services.map((service, serviceIndex) => ({
    id: `${provider.label.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${serviceIndex}`,
    provider: provider.label, name: service.label, category: normalizeCategory(provider.category), price: service.price,
    rating: provider.rating, reviews: provider.reviews, distance: provider.distance,
    image: service.image || provider.heroImg || provider.providerImage || '/assets/ai-banner-home-cleaning.jpg',
    heroImg: provider.heroImg, providerImage: provider.providerImage || provider.logoImg, description: service.desc,
    providerBg: providerColours[providerIndex % providerColours.length], providerEmoji: providerInitials(provider.label),
  }))),
  ...supplemental,
]

const itemParams = (item: CatalogItem) => ({
  id: item.id, provider: item.provider, name: item.name, category: item.category, price: item.price.toFixed(2), rating: item.rating,
  reviews: item.reviews, image: item.image, heroImg: item.heroImg || item.image, providerImage: item.providerImage || item.image,
  description: item.description, providerBg: item.providerBg, providerEmoji: item.providerEmoji,
})

const heading = (eyebrow: string, title: string, copy: string) => <div><p className="text-[11px] font-black uppercase tracking-[.17em] text-[#0967ff]">{eyebrow}</p><h1 className="mt-2 text-3xl font-black tracking-[-.045em] text-[#102044] sm:text-4xl">{title}</h1><p className="mt-3 max-w-2xl text-sm font-semibold leading-7 text-[#6d7b94]">{copy}</p></div>

export function DesktopDiscoverySections({ navigate }: { navigate: Navigate }) {
  const { pendingReview, clearPendingReview } = useNav()
  const featured = [FULL_CATALOG[5], FULL_CATALOG[16], FULL_CATALOG[29]]
  const popular = Object.values(PROVIDERS).slice(0, 5)
  return <div className="space-y-8">
    {pendingReview && <div className="fixed inset-0 z-[80] grid place-items-center bg-[#071331]/55 p-5 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-[28px] bg-white p-7 text-center shadow-2xl"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-amber-50 text-amber-500"><Star size={26} fill="currentColor"/></span><p className="mt-5 text-[11px] font-black uppercase tracking-[.16em] text-[#0967ff]">QUICK FEEDBACK</p><h2 className="mt-2 text-2xl font-black">How was {pendingReview.provider}?</h2><p className="mt-2 text-sm font-semibold leading-6 text-[#75839d]">Your review helps neighbours book with confidence and providers keep improving.</p><button onClick={() => { clearPendingReview(); navigate('reviews', pendingReview) }} className="mt-6 w-full rounded-xl bg-[#0967ff] py-3.5 text-sm font-black text-white">Leave a review</button><button onClick={clearPendingReview} className="mt-3 text-sm font-black text-[#75839d]">Maybe later</button></div></div>}
    <section><SectionHeader eyebrow="MADE FOR YOUR WEEK" title="Deals for you" action="See all deals" onClick={() => navigate('deals')} /><div className="grid gap-5 lg:grid-cols-3">{[
      ['Fresh-home reset', '20% off selected cleaning services', '/assets/ai-banner-home-cleaning.jpg', FULL_CATALOG[0]],
      ['A little glow', 'Beauty packages from QAR 120', '/assets/ai-banner-glow-salon.jpg', FULL_CATALOG.find(x => x.provider === 'Glow Salon & Spa')!],
      ['Drive out spotless', 'Premium car care on your schedule', '/assets/ai-banner-sparkle-carwash.jpg', FULL_CATALOG.find(x => x.provider === 'Sparkle Auto Wash')!],
    ].map(([title, copy, image, item]) => <button key={title as string} onClick={() => navigate('service-detail', itemParams(item as CatalogItem))} className="group relative h-52 overflow-hidden rounded-[26px] text-left shadow-sm"><img src={image as string} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute inset-0 bg-gradient-to-t from-[#06163c]/90 via-[#06163c]/15 to-transparent"/><span className="absolute inset-x-5 bottom-5 text-white"><span className="text-xl font-black">{title as string}</span><span className="mt-1 block text-sm font-semibold text-blue-100">{copy as string}</span></span></button>)}</div></section>
    <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><div><SectionHeader eyebrow="PEOPLE NEAR YOU LOVE" title="Popular providers" action="View providers" onClick={() => navigate('providers')} /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{popular.slice(0, 3).map(provider => <ProviderMini key={provider.label} provider={provider} navigate={navigate}/>)}</div></div><div className="relative overflow-hidden rounded-[28px] bg-[#0967ff] p-7 text-white"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full border-[24px] border-white/10"/><BadgeCheck size={28}/><h2 className="mt-8 text-2xl font-black">Grow with Helpy</h2><p className="mt-2 text-sm font-semibold leading-6 text-blue-100">Join trusted businesses serving customers across Qatar.</p><button onClick={() => navigate('contact-us')} className="mt-6 rounded-xl bg-white px-4 py-3 text-sm font-black text-[#0967ff]">Become a provider <ArrowRight size={15} className="ml-1 inline"/></button></div></section>
    <section><SectionHeader eyebrow="OFFERS & EXPERIENCES" title="Something different this week" action="Explore events" onClick={() => navigate('offers-events')} /><div className="grid gap-5 md:grid-cols-3">{featured.map(item => <CatalogCard key={item.id} item={item} navigate={navigate}/>)}</div></section>
  </div>
}

export function DesktopExploreView({ screen, params, navigate }: { screen: Screen; params: any; navigate: Navigate }) {
  const [search, setSearch] = useState(params?.query || '')
  const [sort, setSort] = useState<'recommended' | 'rating' | 'price'>('recommended')
  const [category, setCategory] = useState('All')
  const screenCategory = screen === 'category-services' ? PWA_CATEGORIES.find(cat => cat[0] === params?.id) : undefined
  const mapped = screenCategory ? (CATEGORY_MAP[screenCategory[0]] || [screenCategory[1]]) : null
  const allCategories = ['All', ...Array.from(new Set(FULL_CATALOG.map(item => item.category)))]
  const filtered = useMemo(() => {
    let items = FULL_CATALOG.filter(item => (!mapped || mapped.includes(item.category)) && (category === 'All' || item.category === category) && `${item.name} ${item.provider} ${item.category}`.toLowerCase().includes(search.toLowerCase()))
    if (sort === 'rating') items = [...items].sort((a, b) => Number(b.rating) - Number(a.rating))
    if (sort === 'price') items = [...items].sort((a, b) => a.price - b.price)
    return items
  }, [category, mapped, search, sort])

  if (screen === 'categories') return <div>{heading('EVERYDAY, COVERED', 'Browse every category', 'The full PWA category library, organised for a faster desktop experience.')}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-5">{PWA_CATEGORIES.map(([id, label, image]) => <button key={id} onClick={() => navigate('category-services', { id, label })} className="group overflow-hidden rounded-[24px] border border-blue-100 bg-white p-4 text-left shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-blue-100"><div className="h-32 overflow-hidden rounded-2xl bg-[#f4f8ff]"><img src={image} alt="" className="h-full w-full object-contain transition duration-300 group-hover:scale-110"/></div><div className="mt-4 flex items-center justify-between gap-3"><div><h2 className="font-black text-[#102044]">{label}</h2><p className="mt-1 text-xs font-semibold text-[#7b89a1]">Explore trusted providers</p></div><ChevronRight size={18} className="text-[#0967ff]"/></div></button>)}</div></div>

  if (screen === 'providers') return <div>{heading('THE HELPY STANDARD', 'Providers people love', 'Verified local businesses, clear service menus and genuine customer feedback.')}<div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{Object.values(PROVIDERS).map(provider => <ProviderCard key={provider.label} provider={provider} navigate={navigate}/>)}</div></div>

  if (screen === 'deals' || screen === 'offers-events') return <DealsView events={screen === 'offers-events'} navigate={navigate}/>

  return <div>{heading(screenCategory ? 'CURATED FOR YOU' : 'EVERY SERVICE IN ONE PLACE', screenCategory ? screenCategory[1] : 'Find the right service', screenCategory ? 'Compare every matching provider, service option and price.' : `${FULL_CATALOG.length} service options from trusted businesses across Qatar.`)}
    <div className="mt-7 rounded-[22px] border border-blue-100 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 xl:flex-row"><div className="relative flex-1"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#8290a9]"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search services, providers and categories" className="h-12 w-full rounded-xl bg-[#f5f8fd] pl-11 pr-4 text-sm font-semibold outline-none focus:ring-2 focus:ring-blue-100"/></div>{!screenCategory && <div className="flex gap-2 overflow-x-auto">{allCategories.map(item => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-xl px-3 py-2 text-xs font-black ${category === item ? 'bg-[#0967ff] text-white' : 'bg-[#f5f8fd] text-[#60708c]'}`}>{item}</button>)}</div>}<select value={sort} onChange={e => setSort(e.target.value as typeof sort)} className="h-12 rounded-xl border-0 bg-[#f5f8fd] px-4 text-xs font-black text-[#60708c] outline-none"><option value="recommended">Recommended</option><option value="rating">Highest rated</option><option value="price">Lowest price</option></select></div></div>
    <div className="mt-6 flex items-center justify-between"><p className="text-sm font-bold text-[#75839d]">{filtered.length} services available</p><button className="inline-flex items-center gap-2 text-xs font-black text-[#0967ff]"><SlidersHorizontal size={15}/>Availability & provider filters</button></div>
    <div className="mt-4 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(item => <CatalogCard key={item.id} item={item} navigate={navigate}/>)}</div>
    {!filtered.length && <div className="mt-6 rounded-[26px] bg-white py-16 text-center ring-1 ring-blue-100"><Search className="mx-auto text-blue-300"/><h2 className="mt-4 text-xl font-black">No matching services</h2><button onClick={() => { setSearch(''); setCategory('All') }} className="mt-4 text-sm font-black text-[#0967ff]">Clear filters</button></div>}
  </div>
}

export function DesktopProviderBooking({ params, navigate }: { params: any; navigate: Navigate }) {
  const fallbackItem = FULL_CATALOG.find(item => item.provider === params?.provider) || FULL_CATALOG[0]
  const provider = PROVIDERS[params?.provider] || ({ label: fallbackItem.provider, category: fallbackItem.category, desc: fallbackItem.description, heroImg: fallbackItem.heroImg || fallbackItem.image, providerImage: fallbackItem.providerImage || fallbackItem.image, rating: fallbackItem.rating, reviews: fallbackItem.reviews, distance: fallbackItem.distance, duration: '~60 to 90 minutes', services: [{ label: fallbackItem.name, desc: fallbackItem.description, price: fallbackItem.price, icon: Sparkles, image: fallbackItem.image }], extras: [] } satisfies ProviderConfig)
  const firstIndex = Math.max(0, provider.services.findIndex(service => service.label.toLowerCase() === String(params?.name || '').toLowerCase()))
  const [selected, setSelected] = useState<number[]>([firstIndex])
  const [extras, setExtras] = useState<number[]>([])
  const [date, setDate] = useState('Today')
  const [time, setTime] = useState('10:00 AM')
  const [ownEquipment, setOwnEquipment] = useState(false)
  const total = selected.reduce((sum, index) => sum + provider.services[index].price, 0) + extras.reduce((sum, index) => sum + provider.extras[index].price, 0) - (provider.label === 'Scrubs Cleaning' && ownEquipment ? 25 : 0)
  const toggle = (index: number, setter: typeof setSelected) => setter(current => current.includes(index) ? (current.length > 1 ? current.filter(value => value !== index) : current) : [...current, index])
  const checkout = () => navigate('booking-checkout', { provider: provider.label, name: selected.map(index => provider.services[index].label).join(' + '), selectedServices: selected.map(index => provider.services[index]), extras: extras.map(index => provider.extras[index]), price: total.toFixed(2), date, time, rating: provider.rating, reviews: provider.reviews, category: normalizeCategory(provider.category), image: provider.heroImg || provider.providerImage, heroImg: provider.heroImg, providerImage: provider.providerImage || provider.logoImg, providerBg: 'bg-blue-500', providerEmoji: providerInitials(provider.label), description: provider.desc })
  return <div className="grid gap-7 xl:grid-cols-[minmax(0,1fr)_390px]"><div className="space-y-6"><section className="relative min-h-[330px] overflow-hidden rounded-[30px] bg-[#102044]"><img src={provider.heroImg || provider.providerImage} alt="" className="absolute inset-0 h-full w-full object-cover opacity-80"/><div className="absolute inset-0 bg-gradient-to-r from-[#071b52]/95 via-[#071b52]/65 to-transparent"/><div className="relative flex min-h-[330px] max-w-2xl flex-col justify-end p-8 text-white sm:p-10"><span className="w-fit rounded-full bg-white/15 px-3 py-1 text-xs font-black backdrop-blur">{normalizeCategory(provider.category)}</span><h1 className="mt-4 text-4xl font-black tracking-[-.05em]">{provider.label}</h1><p className="mt-2 text-base font-semibold text-blue-100">{provider.desc}</p><div className="mt-5 flex flex-wrap gap-4 text-xs font-black"><span><Star size={15} className="mr-1 inline fill-amber-400 text-amber-400"/>{provider.rating} ({provider.reviews})</span><span><MapPin size={15} className="mr-1 inline"/>{provider.distance}</span><span><Clock3 size={15} className="mr-1 inline"/>{provider.duration}</span><span><ShieldCheck size={15} className="mr-1 inline"/>Verified</span></div></div></section>
    <section className="rounded-[28px] border border-blue-100 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Choose your services</h2><p className="mt-1 text-sm font-semibold text-[#75839d]">Select one or combine several services in a single booking.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{provider.services.map((service, index) => { const chosen = selected.includes(index); const Icon = service.icon as ElementType; return <button key={service.label} onClick={() => toggle(index, setSelected)} className={`flex items-start gap-4 rounded-2xl border p-4 text-left transition ${chosen ? 'border-[#0967ff] bg-blue-50 ring-2 ring-blue-100' : 'border-[#e5edf7] hover:border-blue-200'}`}><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl ${chosen ? 'bg-[#0967ff] text-white' : 'bg-[#f4f8fe] text-[#0967ff]'}`}><Icon size={19}/></span><span className="min-w-0 flex-1"><span className="font-black">{service.label}</span><span className="mt-1 block text-xs font-semibold leading-5 text-[#75839d]">{service.desc}</span><span className="mt-2 block text-sm font-black text-[#0967ff]">QAR {service.price}</span></span><span className={`grid h-6 w-6 place-items-center rounded-full ${chosen ? 'bg-[#0967ff] text-white' : 'border border-slate-200'}`}>{chosen && <Check size={14}/>}</span></button>})}</div></section>
    {provider.label === 'Scrubs Cleaning' && <section className="rounded-[26px] border border-blue-100 bg-white p-6 shadow-sm"><h2 className="font-black">Cleaning equipment</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Choice active={!ownEquipment} onClick={() => setOwnEquipment(false)} title="Provider brings equipment" copy="Everything needed is included"/><Choice active={ownEquipment} onClick={() => setOwnEquipment(true)} title="Use my equipment" copy="Save QAR 25 on this booking"/></div></section>}
    {!!provider.extras.length && <section className="rounded-[28px] border border-blue-100 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Make it just right</h2><p className="mt-1 text-sm font-semibold text-[#75839d]">Optional extras from the PWA service menu.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{provider.extras.map((extra, index) => <button key={extra.label} onClick={() => setExtras(current => current.includes(index) ? current.filter(value => value !== index) : [...current, index])} className={`rounded-2xl border p-4 text-left ${extras.includes(index) ? 'border-[#0967ff] bg-blue-50' : 'border-[#e5edf7]'}`}><span className="block text-sm font-black">{extra.label}</span><span className="mt-1 block text-xs font-bold text-[#0967ff]">+ QAR {extra.price}</span></button>)}</div></section>}
  </div><aside className="h-fit rounded-[28px] border border-blue-100 bg-white p-6 shadow-sm xl:sticky xl:top-28"><p className="text-[11px] font-black uppercase tracking-[.16em] text-[#0967ff]">YOUR BOOKING</p><h2 className="mt-2 text-2xl font-black">Choose a time</h2><p className="mt-5 text-sm font-black">Day</p><div className="mt-3 grid grid-cols-3 gap-2">{['Today', 'Tomorrow', 'Fri, 12'].map(value => <button key={value} onClick={() => setDate(value)} className={`rounded-xl py-3 text-xs font-black ${date === value ? 'bg-[#0967ff] text-white' : 'bg-[#f4f8fe] text-[#60708c]'}`}>{value}</button>)}</div><p className="mt-5 text-sm font-black">Available time</p><div className="mt-3 grid grid-cols-2 gap-2">{['08:00 AM', '10:00 AM', '12:00 PM', '02:00 PM', '04:00 PM', '06:00 PM'].map(value => <button key={value} onClick={() => setTime(value)} className={`rounded-xl py-2.5 text-xs font-black ${time === value ? 'bg-[#0967ff] text-white' : 'bg-[#f4f8fe] text-[#60708c]'}`}>{value}</button>)}</div><div className="my-6 h-px bg-[#e9eff8]"/>{selected.map(index => <div key={index} className="mb-2 flex justify-between gap-3 text-sm"><span className="font-semibold text-[#66758f]">{provider.services[index].label}</span><span className="font-black">QAR {provider.services[index].price}</span></div>)}{extras.map(index => <div key={index} className="mb-2 flex justify-between gap-3 text-xs"><span className="font-semibold text-[#7b89a1]">{provider.extras[index].label}</span><span className="font-bold">+ {provider.extras[index].price}</span></div>)}<div className="mt-4 flex items-end justify-between border-t border-[#e9eff8] pt-4"><span className="font-black">Total</span><span className="text-2xl font-black text-[#0967ff]">QAR {total}</span></div><button onClick={checkout} className="mt-5 w-full rounded-xl bg-[#0967ff] py-3.5 text-sm font-black text-white shadow-lg shadow-blue-200">Continue to checkout <ArrowRight size={15} className="ml-1 inline"/></button></aside></div>
}

export function DesktopBookings({ screen, params, navigate }: { screen: Screen; params: any; navigate: Navigate }) {
  const { bookedServices } = useNav()
  const defaults: BookedService[] = [
    { id: 'default-active', provider: 'Scrubs Cleaning', service: 'General Cleaning', date: 'Friday, 12 June', time: '10:00 AM', price: '160.00', status: 'Confirmed', providerBg: 'bg-red-500', providerEmoji: 'SC', providerImage: '/assets/scrubs-leaf-logo-clean.png', addressLabel: 'Home', address: 'West Bay, Doha' },
    { id: 'default-done', provider: 'Glow Salon & Spa', service: 'Beauty Day Package', date: '28 May 2024', time: '2:00 PM', price: '120.00', status: 'Completed', providerBg: 'bg-pink-500', providerEmoji: 'GS', providerImage: '/assets/ai-profile-glow-salon.jpg', addressLabel: 'Home', address: 'The Pearl, Doha' },
  ]
  const all = [...bookedServices, ...defaults]
  const selected = screen === 'order-detail' ? (all.find(item => item.id === params?.id) || ({ ...params, id: params?.id || 'detail', service: params?.service || params?.name } as BookedService)) : null
  const [tab, setTab] = useState<'active' | 'completed'>('active')
  if (selected) return <div>{heading('BOOKING DETAILS', selected.service, `${selected.provider} · ${selected.status}`)}<div className="mt-8 grid gap-6 xl:grid-cols-[1fr_360px]"><section className="rounded-[28px] border border-blue-100 bg-white p-7 shadow-sm"><BookingIdentity booking={selected}/><div className="mt-7 grid gap-4 sm:grid-cols-3"><Info label="Date" value={selected.date}/><Info label="Time" value={selected.time}/><Info label="Location" value={`${selected.addressLabel || 'Home'} · ${selected.address || 'West Bay, Doha'}`}/></div><div className="mt-7 rounded-2xl bg-[#f6f9fe] p-5"><p className="text-sm font-black">Payment summary</p><div className="mt-4 flex justify-between text-sm font-semibold text-[#66758f]"><span>Service total</span><span>QAR {selected.price}</span></div><div className="mt-3 flex justify-between border-t border-blue-100 pt-3 font-black"><span>Paid securely</span><span className="text-[#0967ff]">QAR {selected.price}</span></div></div></section><aside className="h-fit rounded-[26px] bg-[#071b52] p-6 text-white"><MessageCircle/><h2 className="mt-5 text-xl font-black">Need anything?</h2><p className="mt-2 text-sm font-semibold leading-6 text-blue-100">Message the provider directly or ask Helpy support about this booking.</p><button onClick={() => navigate('chat-thread', { name: selected.provider, ...selected })} className="mt-6 w-full rounded-xl bg-white py-3 text-sm font-black text-[#0967ff]">Message provider</button>{selected.status === 'Completed' && <button onClick={() => navigate('reviews', selected)} className="mt-3 w-full rounded-xl border border-white/20 py-3 text-sm font-black">Leave a review</button>}</aside></div></div>
  const shown = all.filter(item => tab === 'completed' ? item.status === 'Completed' : item.status !== 'Completed')
  return <div>{heading('MY BOOKINGS', 'Every booking, easy to follow', 'Track upcoming services, revisit completed work and contact your provider from one place.')}<div className="mt-7 inline-flex rounded-xl bg-white p-1 ring-1 ring-blue-100">{(['active', 'completed'] as const).map(value => <button key={value} onClick={() => setTab(value)} className={`rounded-lg px-5 py-2.5 text-sm font-black capitalize ${tab === value ? 'bg-[#0967ff] text-white' : 'text-[#66758f]'}`}>{value}</button>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-2">{shown.map(item => <button key={item.id} onClick={() => navigate('order-detail', item)} className="rounded-[24px] border border-blue-100 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><BookingIdentity booking={item}/><div className="mt-5 flex items-center justify-between border-t border-[#edf1f7] pt-4"><span className="text-xs font-bold text-[#75839d]">{item.date} · {item.time}</span><span className="text-sm font-black text-[#0967ff]">View details <ArrowRight size={14} className="inline"/></span></div></button>)}</div>{!shown.length && <div className="mt-5 rounded-[26px] bg-white py-16 text-center ring-1 ring-blue-100"><PackageCheck className="mx-auto text-blue-300"/><h2 className="mt-3 font-black">Nothing here yet</h2></div>}</div>
}

export function DesktopMessages({ navigate }: { navigate: Navigate }) {
  const { bookedServices } = useNav()
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState<'All' | 'Bookings' | 'Offers' | 'Support'>('All')
  const base = [
    ['Scrubs Cleaning', 'Your team will arrive at 10:00 AM.', 'Bookings', '/assets/scrubs-leaf-logo-clean.png'], ['Glow Salon & Spa', 'Your beauty package is confirmed.', 'Bookings', '/assets/ai-profile-glow-salon.jpg'],
    ['Helpy Support', 'How can we make your day easier?', 'Support', '/assets/ai-avatar-support.jpg'], ['Sparkle Auto Wash', 'Weekend detailing offer: save 15%.', 'Offers', '/assets/ai-profile-sparkle-carwash.jpg'],
    ['QuickFix Maintenance', 'The technician has shared an update.', 'Bookings', '/assets/ai-avatar-quickfix.jpg'], ['FreshFold Laundry', 'Your laundry is ready for delivery.', 'Bookings', '/assets/ai-provider-freshfold-real-logo.png'],
  ]
  const dynamic = bookedServices.map(item => [item.provider, `${item.service} is ${item.status.toLowerCase()}.`, 'Bookings', item.providerImage || ''] as string[])
  const messages = [...dynamic, ...base].filter(item => (filter === 'All' || item[2] === filter) && `${item[0]} ${item[1]}`.toLowerCase().includes(query.toLowerCase()))
  return <div>{heading('MESSAGES', 'Conversations that keep things moving', 'Search booking updates, provider messages, offers and Helpy support.')}<div className="mt-7 grid min-h-[620px] overflow-hidden rounded-[28px] border border-blue-100 bg-white shadow-sm lg:grid-cols-[390px_1fr]"><section className="border-r border-[#e8eef7]"><div className="p-4"><div className="relative"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#8290a9]"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search conversations" className="h-11 w-full rounded-xl bg-[#f5f8fd] pl-10 pr-3 text-sm font-semibold outline-none"/></div><div className="mt-3 flex gap-2 overflow-auto">{(['All', 'Bookings', 'Offers', 'Support'] as const).map(value => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg px-3 py-2 text-[11px] font-black ${filter === value ? 'bg-[#0967ff] text-white' : 'bg-[#f5f8fd] text-[#66758f]'}`}>{value}</button>)}</div></div><div className="border-t border-[#edf1f7]">{messages.map((item, index) => <button key={`${item[0]}-${index}`} onClick={() => navigate('chat-thread', { name: item[0], providerImage: item[3], providerEmoji: providerInitials(item[0]) })} className="flex w-full gap-3 border-b border-[#edf1f7] p-4 text-left transition hover:bg-blue-50/50"><Avatar name={item[0]} image={item[3]}/><span className="min-w-0 flex-1"><span className="flex justify-between gap-2"><span className="truncate text-sm font-black">{item[0]}</span><span className="text-[10px] font-bold text-[#9aa6b9]">Now</span></span><span className="mt-1 block truncate text-xs font-semibold text-[#75839d]">{item[1]}</span></span></button>)}</div></section><section className="flex items-center justify-center bg-[#f8faff] p-8 text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-[#0967ff]"><MessageCircle size={28}/></span><h2 className="mt-5 text-xl font-black">Choose a conversation</h2><p className="mt-2 max-w-sm text-sm font-semibold leading-6 text-[#75839d]">Open a message to coordinate details with a provider or get support from Helpy.</p></div></section></div></div>
}

export function DesktopReviews({ params, navigate }: { params: any; navigate: Navigate }) {
  const provider = params?.provider || 'Scrubs Cleaning'
  const [stars, setStars] = useState(0)
  const [service, setService] = useState('All services')
  const services = PROVIDERS[provider]?.services.map(item => item.label) || [params?.service || params?.name || 'General Cleaning']
  const reviews = [
    ['Maha A.', 5, services[0], 'Careful, punctual and genuinely professional. Everything felt easy from booking to finish.'],
    ['Omar K.', 5, services[Math.min(1, services.length - 1)], 'Clear communication and excellent work. I would happily book again.'],
    ['Leena R.', 4, services[0], 'A very smooth experience and the provider paid attention to the small details.'],
    ['Yousef M.', 5, services[Math.min(2, services.length - 1)], 'Arrived on time, explained the process and delivered exactly what was promised.'],
    ['Noor S.', 3, services[0], 'The service was good overall and support responded quickly to my question.'],
  ].filter(review => (!stars || review[1] === stars) && (service === 'All services' || review[2] === service))
  return <div>{heading('CUSTOMER REVIEWS', `What people say about ${provider}`, 'Verified feedback from customers who completed a booking through Helpy.')}<div className="mt-7 grid items-start gap-6 xl:grid-cols-[300px_1fr]"><aside className="rounded-[26px] border border-blue-100 bg-white p-6 shadow-sm"><div className="text-center"><p className="text-5xl font-black text-[#102044]">{params?.rating || PROVIDERS[provider]?.rating || '4.8'}</p><div className="mt-2 flex justify-center gap-1 text-amber-400">{[1,2,3,4,5].map(value => <Star key={value} size={17} fill="currentColor"/>)}</div><p className="mt-2 text-xs font-bold text-[#75839d]">{params?.reviews || PROVIDERS[provider]?.reviews || '120'} verified reviews</p></div><div className="my-6 h-px bg-[#edf1f7]"/><p className="text-sm font-black">Filter by rating</p><div className="mt-3 grid grid-cols-3 gap-2">{[0,5,4,3,2,1].map(value => <button key={value} onClick={() => setStars(value)} className={`rounded-lg py-2 text-xs font-black ${stars === value ? 'bg-[#0967ff] text-white' : 'bg-[#f4f8fe] text-[#66758f]'}`}>{value || 'All'}{value ? ' ★' : ''}</button>)}</div><p className="mt-5 text-sm font-black">Service</p><select value={service} onChange={e => setService(e.target.value)} className="mt-3 h-11 w-full rounded-xl bg-[#f4f8fe] px-3 text-xs font-black outline-none"><option>All services</option>{services.map(value => <option key={value}>{value}</option>)}</select></aside><section className="space-y-4">{reviews.map((review, index) => <article key={index} className="rounded-[24px] border border-blue-100 bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><Avatar name={review[0] as string}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-black">{review[0] as string}</p><p className="mt-1 text-xs font-bold text-[#0967ff]">{review[2] as string} · Verified booking</p></div><div className="flex text-amber-400">{Array.from({ length: review[1] as number }).map((_, star) => <Star key={star} size={14} fill="currentColor"/>)}</div></div><p className="mt-4 text-sm font-semibold leading-7 text-[#5f6f8a]">{review[3] as string}</p></div></div></article>)}{!reviews.length && <div className="rounded-[24px] bg-white py-14 text-center ring-1 ring-blue-100"><Filter className="mx-auto text-blue-300"/><p className="mt-3 font-black">No reviews match these filters.</p></div>}<button onClick={() => navigate('service-detail', params)} className="inline-flex items-center gap-2 text-sm font-black text-[#0967ff]">Back to provider <ArrowRight size={15}/></button></section></div></div>
}

function DealsView({ events, navigate }: { events: boolean; navigate: Navigate }) {
  const cards = events ? supplemental.filter(item => item.category === 'Events') : [FULL_CATALOG[1], FULL_CATALOG.find(item => item.provider === 'Glow Salon & Spa')!, FULL_CATALOG.find(item => item.provider === 'Sparkle Auto Wash')!, FULL_CATALOG.find(item => item.provider === 'FreshFold Laundry')!]
  return <div>{heading(events ? 'OFFERS & EVENTS' : 'A LITTLE EXTRA', events ? 'Make more of the moment' : 'Deals worth taking', events ? 'Event planning and seasonal experiences from trusted local teams.' : 'Useful offers from providers people already trust.')}<div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{cards.map((item, index) => <div key={item.id} className="overflow-hidden rounded-[26px] border border-blue-100 bg-white shadow-sm"><div className="relative h-44"><img src={item.image} alt="" className="h-full w-full object-cover"/><span className="absolute left-4 top-4 rounded-full bg-[#d9ff21] px-3 py-1 text-[10px] font-black text-[#102044]">{events ? 'BOOK AHEAD' : `${10 + index * 5}% OFF`}</span></div><div className="p-5"><p className="text-xs font-black text-[#0967ff]">{item.provider}</p><h2 className="mt-2 text-lg font-black">{item.name}</h2><p className="mt-2 text-sm font-semibold leading-6 text-[#75839d]">{item.description}</p><button onClick={() => navigate('service-detail', itemParams(item))} className="mt-5 text-sm font-black text-[#0967ff]">Explore offer <ArrowRight size={14} className="inline"/></button></div></div>)}</div></div>
}

function CatalogCard({ item, navigate }: { item: CatalogItem; navigate: Navigate }) { const [saved, setSaved] = useState(false); return <article className="group overflow-hidden rounded-[24px] border border-blue-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl hover:shadow-blue-100"><div className="relative h-44 overflow-hidden bg-blue-50"><img src={item.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><button onClick={() => setSaved(value => !value)} className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-xl bg-white/90 text-[#102044] shadow" aria-label="Save service"><Heart size={16} className={saved ? 'fill-rose-500 text-rose-500' : ''}/></button><span className="absolute bottom-3 left-3 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-black text-[#0967ff] backdrop-blur">{item.category}</span></div><button onClick={() => navigate('service-detail', itemParams(item))} className="w-full p-5 text-left"><p className="text-xs font-black text-[#0967ff]">{item.provider}</p><h2 className="mt-1 truncate text-lg font-black">{item.name}</h2><p className="mt-2 line-clamp-2 min-h-10 text-xs font-semibold leading-5 text-[#75839d]">{item.description}</p><div className="mt-4 flex items-end justify-between"><div><p className="text-[10px] font-bold text-[#93a0b5]">from</p><p className="text-lg font-black">QAR {item.price}</p></div><span className="text-xs font-black text-[#66758f]"><Star size={14} className="mr-1 inline fill-amber-400 text-amber-400"/>{item.rating} ({item.reviews})</span></div></button></article> }
function ProviderCard({ provider, navigate }: { provider: ProviderConfig; navigate: Navigate }) { return <button onClick={() => navigate('service-detail', itemParams(FULL_CATALOG.find(item => item.provider === provider.label)!))} className="overflow-hidden rounded-[26px] border border-blue-100 bg-white text-left shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="h-44 overflow-hidden bg-blue-50"><img src={provider.heroImg || provider.providerImage} alt="" className="h-full w-full object-cover"/></div><div className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-black text-[#0967ff]">{normalizeCategory(provider.category)}</p><h2 className="mt-1 text-xl font-black">{provider.label}</h2></div><BadgeCheck className="text-[#0967ff]"/></div><p className="mt-2 text-sm font-semibold leading-6 text-[#75839d]">{provider.desc}</p><div className="mt-4 flex items-center justify-between text-xs font-black"><span><Star size={14} className="mr-1 inline fill-amber-400 text-amber-400"/>{provider.rating} ({provider.reviews})</span><span className="text-[#0967ff]">{provider.services.length} services <ArrowRight size={13} className="inline"/></span></div></div></button> }
function ProviderMini({ provider, navigate }: { provider: ProviderConfig; navigate: Navigate }) { return <button onClick={() => navigate('service-detail', itemParams(FULL_CATALOG.find(item => item.provider === provider.label)!))} className="flex items-center gap-3 rounded-[20px] border border-blue-100 bg-white p-4 text-left shadow-sm"><Avatar name={provider.label} image={provider.providerImage || provider.logoImg}/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-black">{provider.label}</span><span className="mt-1 block text-xs font-semibold text-[#75839d]"><Star size={12} className="mr-1 inline fill-amber-400 text-amber-400"/>{provider.rating} · {provider.distance}</span></span><ChevronRight size={17} className="text-[#0967ff]"/></button> }
function SectionHeader({ eyebrow, title, action, onClick }: { eyebrow: string; title: string; action: string; onClick: () => void }) { return <div className="mb-5 flex items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.17em] text-[#0967ff]">{eyebrow}</p><h2 className="mt-1 text-2xl font-black tracking-[-.035em]">{title}</h2></div><button onClick={onClick} className="text-sm font-black text-[#0967ff]">{action} <ArrowRight size={14} className="inline"/></button></div> }
function Choice({ active, onClick, title, copy }: { active: boolean; onClick: () => void; title: string; copy: string }) { return <button onClick={onClick} className={`rounded-2xl border p-4 text-left ${active ? 'border-[#0967ff] bg-blue-50' : 'border-[#e5edf7]'}`}><span className="flex items-center justify-between"><span className="text-sm font-black">{title}</span><span className={`grid h-5 w-5 place-items-center rounded-full ${active ? 'bg-[#0967ff] text-white' : 'border border-slate-200'}`}>{active && <Check size={12}/>}</span></span><span className="mt-1 block text-xs font-semibold text-[#75839d]">{copy}</span></button> }
function BookingIdentity({ booking }: { booking: BookedService }) { return <div className="flex items-center gap-4"><Avatar name={booking.provider} image={booking.providerImage}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-black text-[#0967ff]">{booking.provider}</p><h2 className="mt-1 truncate text-lg font-black">{booking.service}</h2></div><span className={`rounded-full px-3 py-1.5 text-[10px] font-black ${booking.status === 'Completed' ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-[#0967ff]'}`}>{booking.status}</span></div> }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-[#f6f9fe] p-4"><p className="text-[10px] font-black uppercase tracking-wide text-[#8b98ad]">{label}</p><p className="mt-2 text-sm font-black">{value}</p></div> }
function Avatar({ name, image }: { name: string; image?: string }) { return image ? <img src={image} alt="" className="h-12 w-12 shrink-0 rounded-2xl bg-blue-50 object-cover"/> : <span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#0967ff] text-xs font-black text-white">{providerInitials(name)}</span> }
